"""add conversation memory fields

Revision ID: ada0e5dfbe81
Revises: 62b3728e6023
Create Date: 2026-10-01 14:59:24.864407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ada0e5dfbe81"
down_revision: Union[str, Sequence[str], None] = "62b3728e6023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Sua tay: them server_default='' -- cot NOT NULL moi tren bang DA CO
    # du lieu (du bang conversations truoc gio chua co code nao insert,
    # khong the chac 100% rong tu ben ngoai DB) se FAIL khi ADD COLUMN neu
    # co du lieu cu khong co gia tri cho cot nay. server_default khop dung
    # Python-side default `answer: str = ""` da khai trong models.py.
    op.add_column(
        "conversations",
        sa.Column(
            "answer",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "conversations", sa.Column("conversation_id", sa.Integer(), nullable=True)
    )
    op.add_column("conversations", sa.Column("owner_id", sa.Integer(), nullable=True))
    # Sua tay: dat ten rieng cho 2 constraint (thay vi None Alembic tu sinh)
    # -- downgrade() can ten CU THE de drop_constraint() hoat dong, None se
    # raise loi ngay (xem WARNING cu Alembic tu in ra ben duoi truoc khi sua).
    op.create_foreign_key(
        "fk_conversations_owner_id_users",
        "conversations",
        "users",
        ["owner_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_conversations_conversation_id_conversations",
        "conversations",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_conversations_conversation_id_conversations",
        "conversations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_conversations_owner_id_users", "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "owner_id")
    op.drop_column("conversations", "conversation_id")
    op.drop_column("conversations", "answer")
    # ### end Alembic commands ###
